langauge: java
before_script:
- echo "Starting build"
script:
- mvn clean package
after_script:
- echo "Script finished"
sfter_success:
- echo "Build ready"
- ls -l $TRAVIS_BUILD_DIR/target
after_failure:
- echo "Build failure"
